// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt3CqCrDu2lLVh02TH9t2KysM38QacJ5Y',
    appId: '1:909895170705:web:7f9b93905b21c2919edd30',
    messagingSenderId: '909895170705',
    projectId: 'artlistener-1',
    authDomain: 'artlistener-1.firebaseapp.com',
    storageBucket: 'artlistener-1.firebasestorage.app',
    measurementId: 'G-92DYNVXHQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQi9KonWprJctifAuuQx5IlypKsTg3kR8',
    appId: '1:909895170705:android:2f2ce2e94de548029edd30',
    messagingSenderId: '909895170705',
    projectId: 'artlistener-1',
    storageBucket: 'artlistener-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJKNG5G0tjJw5giqtEc7-G6WmHCsQ9cFc',
    appId: '1:909895170705:ios:458213f41ad4065f9edd30',
    messagingSenderId: '909895170705',
    projectId: 'artlistener-1',
    storageBucket: 'artlistener-1.firebasestorage.app',
    iosBundleId: 'com.example.artlistener1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJKNG5G0tjJw5giqtEc7-G6WmHCsQ9cFc',
    appId: '1:909895170705:ios:458213f41ad4065f9edd30',
    messagingSenderId: '909895170705',
    projectId: 'artlistener-1',
    storageBucket: 'artlistener-1.firebasestorage.app',
    iosBundleId: 'com.example.artlistener1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt3CqCrDu2lLVh02TH9t2KysM38QacJ5Y',
    appId: '1:909895170705:web:146a0ea8fee231d29edd30',
    messagingSenderId: '909895170705',
    projectId: 'artlistener-1',
    authDomain: 'artlistener-1.firebaseapp.com',
    storageBucket: 'artlistener-1.firebasestorage.app',
    measurementId: 'G-65BJ9TS89Z',
  );

}